baseURL = "https://www.cc.osono.nl/"
languageCode = "nl-nl"
title = "Concepts & Creation Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
title = "De blog van Projectgroep 4"
author = "Community Flow"
profilePicture = "images/logo.jpeg"
keywords = "Blog"
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/group.jpg"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# [[params.socialIcons]]
# icon = "fa-linkedin"
# title = "Linkedin"
# url = ""

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/OssamaSijbesma/windesheim-cc-blog"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:ossama_sybesma@hotmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Berichten"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Over ons"
  weight = 300
  identifier = "about"
  url = "/about/"